### ISSUE TITLE
Source files are duplicated in bundle for every import

### ISSUE THREAD

**Issue by jelbourn** [SimplrJS/scss-bundle#16] opened 2017-04-09 01:12 UTC
The tool currently outputs each scss file into the bundle every time it is encountered. The bundle would end up significantly smaller if each scss file were only emitted the first time it is encountered. 

#### To reproduce
* Clone https://github.com/angular/material2
* `./node_modules/.bin/scss-bundle -e ./src/lib/core/theming/_all-theme.scss -d /tmp/out.scss`

Note that the content of, for example, `_palette.scss` is included 40+ times in the output.

**Comment by DovydasNavickas** [comment] 2017-04-09 03:00
Good catch! 👏 

It is a fairly easy solution to emit the content of duplicate `@import` only once, but it might have unexpected results in some cases, though.

Consider a variable being set in the import such as your mentioned `_palette.scss`:
```scss
$my-var: red;
```
Then, it is overridden later in the stack as such:
```scss
$my-var: blue;
```

And the `_palette.scss` is imported again, which should reset the `$my-var` to `red` again, wouldn't it?

But if we omit the output of the second `@import`, the value of `$my-var` is going to stay `blue`.

Of course, a proper usage of `@import` and variables would be with [`!default` ](https://robots.thoughtbot.com/sass-default) suffix and compilation would work as expected in both cases. But it's easy to miss one `!default` and the rest of the day is going to be spent on debugging.

Possible solutions would be:
- Checking if all variables have `!default` suffix or are not used later on in the stack
- Adding a mode for duplicate imports and stating in README that `developer MUST use !default suffix`  to have expected results

The first solution would make this package enormously more complex and would require some kind of AST analysis of the whole SCSS stack.

The second one would be error prone, even if we warn developers of possible consequences, especially for the project of `material2` size.

### Example for duplicate imports

I've added an example with duplicate imports [here](https://github.com/SimplrJS/scss-bundle/tree/1be9d85b1254dbc8b4c06aa4ff0e441cdc295802/examples/duplicate-import).

Files `b` and `c` import file `a`, which has a variable `$my-var` without `!default` suffix.

File `main.scss` has imports done like this:
```
b.scss
a.scss
c.scss
a.scss
```

And I've added import of file `duplicate` after each import for an easy visual output when compiling into css.

The output of `main.scss` file after `scss-bundle` is this (I removed unnecessary empty lines):
```scss
$my-var: red;
.b {
    color: darken($my-var, 15);
}
$my-var: blue;
.b:hover {
    color: darken($my-var, 15);
}
._____{
    color: $my-var;
}
$my-var: red;
._____{
    color: $my-var;
}
$my-var: red;
.c {
    color: darken($my-var, 15);
}
$my-var: green;

.c:hover {
    color: darken($my-var, 15);
}
._____{
    color: $my-var;
}
$my-var: red;
._____{
    color: $my-var;
}
```
And if we import `a.scss` only once, on first occurance:
```scss
$my-var: red;
.b {
    color: darken($my-var, 15);
}
$my-var: blue;
.b:hover {
    color: darken($my-var, 15);
}
._____{
    color: $my-var;
}
/* omitted red */
._____{
    color: $my-var;
}
/* omitted red */
.c {
    color: darken($my-var, 15);
}
$my-var: green;

.c:hover {
    color: darken($my-var, 15);
}
._____{
    color: $my-var;
}
/* omitted red */
._____{
    color: $my-var;
}
```

You should be able to see that the outputs are going to be different, even without compilation, but for the sake of completeness..

<details> 
  <summary>Here is the first result compiled into CSS (I removed the comments):</summary>

```css
.b {
  color: #b30000; }

.b:hover {
  color: #0000b3; }

._____ {
  color: blue; }

._____ {
  color: red; }

.c {
  color: #b30000; }

.c:hover {
  color: #003400; }

._____ {
  color: green; }

._____ {
  color: red; }
```
</details>

<details> 
  <summary>And the second one</summary>

```css
.b {
  color: #b30000; }

.b:hover {
  color: #0000b3; }

._____ {
  color: blue; }

._____ {
  color: blue; }

.c {
  color: #0000b3; }

.c:hover {
  color: #003400; }

._____ {
  color: green; }

._____ {
  color: green; }

```
</details>


Correct me if my thinking is wrong, but if it's not, then the problem is more complex than simply emitting once, as you can see.

**Comment by DovydasNavickas** [comment] 2017-04-10 17:54
@jelbourn, I looked at what you have in `_palette.scss` and most probably, including it only once wouldn't crash things up.

Maybe adding an option for list of imports to de-dupe would be a good compromise?

This way you could control which files are being de-duped and make sure things do not break.

What do you think?

**Comment by jelbourn** [comment] 2017-04-10 19:08
Adding an option works for me. 

In general, I see the purpose of a scss bundler as a tool for a library authors (as opposed to application authors) to flatten sources so that its consumers have a single entry-point. Through this lens, I'd consider having multiple files that define the same symbols as an anti-pattern. 

For application authors, overriding a non `!default` variable is risky, as there's no explicit contract from the library author that such a variable constitutes a public API.

**Comment by DovydasNavickas** [comment] 2017-04-13 15:44
Done: https://github.com/SimplrJS/scss-bundle/commit/20edbb4e77f66441750efa17f585bbe1c02e840c

@jelbourn, try running:
"node_modules/.bin/scss-bundle" -e ./src/lib/core/theming/_all-theme.scss -d /tmp/out.scss --dedupe src/lib/core/theming/**/_palette.scss

Also, it's way easier to use non-CLI API now with TypeScript. We will update the README soon.

**Comment by DovydasNavickas** [comment] 2017-04-13 15:46
Oh, and install `yarn add scss-bundle@beta` for the moment. I want to test it first, write the README and the publish as `@latest`.

**Comment by krigton** [comment] 2017-04-27 04:31
Why do you bundle all those things together? Why not keep them in separate files. 
For example we do not use any of the palettes, we created our own. I don't see the reason why I would put my sass framework to load those variables (even on compile time) as know I never gonna use them.

**Comment by DovydasNavickas** [comment] 2017-06-21 18:09
I'm closing this issue because no more issues were raised in almost 2 months. Cheers!

**Closed by DovydasNavickas** 2017-06-21 18:09 UTC
Labels: enhancement
